import Navbar from "@/components/Navbar";
import "./globals.scss";


export const metadata = {
  title: "Motion Design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
